In [1]:
import numpy as np


In [2]:
arr1 = np.arange(1, 11)
arr2 = np.random.randint(1, 10, size=(3, 3))

print(arr1)
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10]
[[2 8 8]
 [6 1 4]
 [2 6 1]]


In [3]:
print(arr1.sum())
print(arr1.mean())
print(arr1.max())


55
5.5
10


In [4]:
arr_copy = arr1.copy()
arr_copy[arr_copy > 5] = 0
print(arr_copy)


[1 2 3 4 5 0 0 0 0 0]
